name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend Build and Deploy Steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Frontend Build and Deploy Steps
      - name: Build Frontend Docker image
        run: |
          docker build -t my-frontend-image .

      - name: Log in to Docker Hub for Frontend
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username jyldyz0610 --password-stdin

      - name: Tag Frontend Docker image
        run: |
          docker tag my-frontend-image:latest jyldyz0610/frontend-image:latest

      - name: Push Frontend Docker image to Docker Hub
        run: |
          docker push jyldyz0610/frontend-image:latest

      # JSON Server Setup and Deploy
      - name: Install Docker on EC2 instance
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Copy db.json to EC2 instance
        run: |
          scp -i ${{ secrets.SSH_KEY_PATH }} db.json ubuntu@${{ secrets.EC2_PUBLIC_DNS }}:/home/ubuntu/

      - name: SSH into EC2 instance and deploy JSON Server
        run: |
          ssh -i ${{ secrets.SSH_KEY_PATH }} ubuntu@${{ secrets.EC2_PUBLIC_DNS }} "docker run -d -p 80:80 -v /home/ubuntu/db.json:/data/db.json clue/json-server"

      # Frontend Deploy
      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy Frontend to EC2 instance
        run: |
          scp -r -i ${{ secrets.SSH_KEY_PATH }} build/* ubuntu@${{ secrets.EC2_PUBLIC_DNS }}:/var/www/html/
