name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend Build and Deploy Steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Backend Docker image
        run: |
          docker build -t jyldyz0610/backend-image .

      - name: Log in to Docker Hub for Backend
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username jyldyz0610 --password-stdin

      - name: Tag Backend Docker image
        run: |
          docker tag jyldyz0610/backend-image:latest jyldyz0610/backend-image:latest

      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push jyldyz0610/backend-image:latest

      - name: SSH into EC2 instance and deploy Backend
        run: |
          ssh -i ${{ secrets.SSH_KEY_PATH }} ubuntu@${{ secrets.EC2_PUBLIC_DNS }} "docker pull jyldyz0610/backend-image:latest && docker run -d -p 3000:3000 jyldyz0610/backend-image:latest"

      
      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install frontend dependencies and build
        run: |
          cd frontend-directory
          npm install
          npm run build

      - name: Deploy Frontend to EC2 instance
        run: |
          scp -r -i ${{ secrets.SSH_KEY_PATH }} frontend-directory/build/* ubuntu@${{ secrets.EC2_PUBLIC_DNS }}:/var/www/html/
